### ISSUE TITLE
Incorrect toSeconds value

### ISSUE THREAD

**Issue by winston0410** [tolu/ISO8601-duration#30]
I am not sure if this is a bug or a feature that I don't understand. I get the duration of a year in seconds like this:

```typescript
import { parse, toSeconds } from "iso8601-duration";

console.log(toSeconds(parse('P1Y'))) //31536000
```

And when I get 2 years in seconds, the value seems to be wrong:

```typescript
import { parse, toSeconds } from "iso8601-duration";

console.log(toSeconds(parse('P2Y'))) //It returns 63158400, instead of 63072000
```

Why is that?

**Comment by tolu** [comment]
hi there, sorry for the late reply 🙏 

the reason is that any duration has to have a starting point (an epoch if you will), that being defaulted to `Date.now()` if nothing is provided. And so getting the duration for 2 years only means that the subsequent year might be a leap year or something like that - so it is all calendar related which makes it seem a bit weird, but correct 😊

**Comment by winston0410** [comment]
Yes Ieap year was the issue. Thanks for your reply
